[package]
name = "dbus-codegen"
version = "0.1.0"
authors = ["David Henningsson <diwic@ubuntu.com>"]

[[bin]]
name = "dbus-codegen-rust"
path = "src/main.rs"

[dependencies]
xml-rs = "0.3"
dbus = { path = "../dbus", version = "0.5.4" }
clap = "2.20"
