[package]
authors = ["David Henningsson <diwic@ubuntu.com>"]
name = "dbus-tokio"
version = "0.1.0"

[dependencies]
dbus = { path = "../../dbus" }
futures = "0.1.12"
mio = "0.6.9"
tokio-core = "0.1.8"

[dev-dependencies]
tokio-timer = "0.1.0"
